"""Initial migration for Prop Firm Platform

Revision ID: 7ae8ba41fb86
Revises: 
Create Date: 2026-03-01 18:01:39.137160

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7ae8ba41fb86'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('challenges',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'ARCHIVED', name='challengestatusenum'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Numeric(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('job_execution_log',
    sa.Column('job_name', sa.String(length=100), nullable=False),
    sa.Column('job_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'IN_PROGRESS', 'CANCELLED', name='jobstatusenum'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Numeric(), nullable=True),
    sa.Column('accounts_processed', sa.Numeric(), nullable=True),
    sa.Column('accounts_passed', sa.Numeric(), nullable=True),
    sa.Column('accounts_failed', sa.Numeric(), nullable=True),
    sa.Column('violations_created', sa.Numeric(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('triggered_by', sa.String(length=50), nullable=True),
    sa.Column('execution_context', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('mt5_servers',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('host', sa.String(length=100), nullable=False),
    sa.Column('port', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'MAINTENANCE', 'ERROR', name='mt5serverstatusenum'), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('max_connections', sa.Numeric(), nullable=False),
    sa.Column('current_connections', sa.Numeric(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('encryption_key', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_heartbeat', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('notification_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('type', sa.Enum('ACCOUNT_UPDATE', 'TRADE_ALERT', 'RISK_VIOLATION', 'SYSTEM_ALERT', 'ACCOUNT_PASSED', 'ACCOUNT_FAILED', 'PAYMENT_CONFIRMED', 'DAILY_SUMMARY', 'WEEKLY_REPORT', 'PLATFORM_ANNOUNCEMENT', name='notificationtypeenum'), nullable=False),
    sa.Column('subject', sa.String(length=200), nullable=True),
    sa.Column('title_template', sa.Text(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=False),
    sa.Column('data_template', sa.Text(), nullable=True),
    sa.Column('default_channels', sa.Text(), nullable=False),
    sa.Column('default_priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriorityenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('allow_customization', sa.Boolean(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('use_count', sa.Numeric(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('platform_metrics',
    sa.Column('metric_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_users', sa.Numeric(), nullable=False),
    sa.Column('active_users', sa.Numeric(), nullable=False),
    sa.Column('new_users', sa.Numeric(), nullable=False),
    sa.Column('total_accounts', sa.Numeric(), nullable=False),
    sa.Column('active_accounts', sa.Numeric(), nullable=False),
    sa.Column('passed_accounts', sa.Numeric(), nullable=False),
    sa.Column('failed_accounts', sa.Numeric(), nullable=False),
    sa.Column('new_accounts', sa.Numeric(), nullable=False),
    sa.Column('total_trades', sa.Numeric(), nullable=False),
    sa.Column('total_volume', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('total_revenue', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_account_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_platform_equity', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('payout_ratio', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('avg_win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('platform_drawdown', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sync_success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('risk_evaluation_success_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('metric_date')
    )
    op.create_table('roles',
    sa.Column('name', sa.Enum('SUPER_ADMIN', 'ADMIN', 'TRADER', 'GUEST', name='roleenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('challenge_rule_versions',
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_total_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit_target', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_positions', sa.Numeric(), nullable=False),
    sa.Column('max_lot_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowed_instruments', sa.Text(), nullable=True),
    sa.Column('trading_hours_start', sa.String(length=5), nullable=True),
    sa.Column('trading_hours_end', sa.String(length=5), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('email_queue',
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('recipient_name', sa.String(length=100), nullable=True),
    sa.Column('subject', sa.String(length=200), nullable=False),
    sa.Column('body_html', sa.Text(), nullable=True),
    sa.Column('body_text', sa.Text(), nullable=True),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('sender_email', sa.String(length=255), nullable=False),
    sa.Column('sender_name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.Numeric(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Numeric(), nullable=False),
    sa.Column('max_retries', sa.Numeric(), nullable=False),
    sa.Column('message_id', sa.String(length=255), nullable=True),
    sa.Column('tracking_data', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['template_id'], ['notification_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_email_queue_scheduled_for', 'email_queue', ['scheduled_for'], unique=False)
    op.create_index('ix_email_queue_status_priority', 'email_queue', ['status', 'priority'], unique=False)
    op.create_index('ix_email_queue_template_id', 'email_queue', ['template_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=True),
    sa.Column('last_name', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', postgresql.INET(), nullable=True),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('leaderboard_cache',
    sa.Column('period', sa.String(length=20), nullable=False),
    sa.Column('rank', sa.Numeric(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('trades_count', sa.Numeric(), nullable=False),
    sa.Column('ranking_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('calculated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_leaderboard_cache_period_user_rank', 'leaderboard_cache', ['period', 'user_id', 'rank'], unique=True)
    op.create_table('login_audit_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('SUCCESS', 'FAILED', 'BLOCKED', name='loginstatusenum'), nullable=False),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('payments',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('challenge_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'REFUNDED', 'CANCELLED', name='paymentstatusenum'), nullable=False),
    sa.Column('payment_method', sa.Enum('CREDIT_CARD', 'DEBIT_CARD', 'PAYPAL', 'BANK_TRANSFER', 'CRYPTO', 'SIMULATED', name='paymentmethodenum'), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=True),
    sa.Column('payment_intent_id', sa.String(length=255), nullable=True),
    sa.Column('client_secret', sa.String(length=255), nullable=True),
    sa.Column('payment_metadata', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['challenge_id'], ['challenges.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('transaction_id')
    )
    op.create_table('trader_metrics',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_accounts', sa.Numeric(), nullable=False),
    sa.Column('active_accounts', sa.Numeric(), nullable=False),
    sa.Column('passed_accounts', sa.Numeric(), nullable=False),
    sa.Column('failed_accounts', sa.Numeric(), nullable=False),
    sa.Column('total_trades', sa.Numeric(), nullable=False),
    sa.Column('winning_trades', sa.Numeric(), nullable=False),
    sa.Column('losing_trades', sa.Numeric(), nullable=False),
    sa.Column('total_profit', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_commission', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('total_swap', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('avg_daily_loss', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('max_consecutive_losses', sa.Numeric(), nullable=False),
    sa.Column('days_traded', sa.Numeric(), nullable=False),
    sa.Column('avg_trades_per_day', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_trade_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('win_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('profit_factor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sharpe_ratio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('risk_reward_ratio', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('is_active_trader', sa.Boolean(), nullable=False),
    sa.Column('ranking_score', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_notification_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('in_app_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('sms_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('push_notifications_enabled', sa.Boolean(), nullable=False),
    sa.Column('account_update_enabled', sa.Boolean(), nullable=False),
    sa.Column('trade_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('risk_violation_enabled', sa.Boolean(), nullable=False),
    sa.Column('system_alert_enabled', sa.Boolean(), nullable=False),
    sa.Column('marketing_enabled', sa.Boolean(), nullable=False),
    sa.Column('daily_summary_enabled', sa.Boolean(), nullable=False),
    sa.Column('weekly_report_enabled', sa.Boolean(), nullable=False),
    sa.Column('quiet_hours_start', sa.String(length=5), nullable=True),
    sa.Column('quiet_hours_end', sa.String(length=5), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('email_frequency', sa.String(length=20), nullable=True),
    sa.Column('batch_notifications', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_settings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('notification_email', sa.Boolean(), nullable=True),
    sa.Column('notification_push', sa.Boolean(), nullable=True),
    sa.Column('theme', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('account_number', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING', 'PASSED', 'FAILED', 'LOCKED', 'ARCHIVED', name='accountstatusenum'), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('current_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('daily_start_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('highest_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('mt5_login', sa.String(length=50), nullable=True),
    sa.Column('mt5_password', sa.String(length=100), nullable=True),
    sa.Column('server', sa.String(length=100), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('locked_by', sa.UUID(), nullable=True),
    sa.Column('locked_reason', sa.Text(), nullable=True),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('passed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['locked_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_number'),
    sa.UniqueConstraint('id')
    )
    op.create_table('revenue_ledger',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('revenue_type', sa.Enum('CHALLENGE_SALE', 'ACCOUNT_UPGRADE', 'REFUND', 'FEE', name='revenuetypeenum'), nullable=False),
    sa.Column('is_processed', sa.Boolean(), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('account_rule_snapshots',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('rule_version_id', sa.UUID(), nullable=False),
    sa.Column('max_daily_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_total_loss', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('profit_target', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('max_positions', sa.Numeric(), nullable=False),
    sa.Column('max_lot_size', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('allowed_instruments', sa.Text(), nullable=True),
    sa.Column('trading_hours_start', sa.String(length=5), nullable=True),
    sa.Column('trading_hours_end', sa.String(length=5), nullable=True),
    sa.Column('snapshot_version', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['rule_version_id'], ['challenge_rule_versions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('daily_stats',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('stat_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('starting_balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('ending_balance', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('daily_pnl', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('total_commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_swap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('trade_count', sa.Numeric(), nullable=True),
    sa.Column('winning_trades', sa.Numeric(), nullable=True),
    sa.Column('losing_trades', sa.Numeric(), nullable=True),
    sa.Column('max_drawdown', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_daily_stats_account_date', 'daily_stats', ['account_id', 'stat_date'], unique=True)
    op.create_table('equity_snapshots',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('free_margin', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('margin_level', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_equity_snapshots_account_timestamp', 'equity_snapshots', ['account_id', 'timestamp'], unique=False)
    op.create_table('mt5_accounts',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('server_id', sa.UUID(), nullable=False),
    sa.Column('platform_account_id', sa.UUID(), nullable=False),
    sa.Column('mt5_login', sa.String(length=50), nullable=False),
    sa.Column('mt5_password', sa.String(length=100), nullable=False),
    sa.Column('mt5_investor_password', sa.String(length=100), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('leverage', sa.Numeric(), nullable=False),
    sa.Column('status', sa.Enum('CONNECTED', 'DISCONNECTED', 'SYNCING', 'ERROR', name='mt5accountstatusenum'), nullable=False),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('is_master', sa.Boolean(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('equity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('free_margin', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('margin_level', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('next_sync_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_interval_seconds', sa.Numeric(), nullable=False),
    sa.Column('error_count', sa.Numeric(), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_error_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['platform_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['server_id'], ['mt5_servers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('mt5_login')
    )
    op.create_index('ix_mt5_accounts_status', 'mt5_accounts', ['status'], unique=False)
    op.create_index('ix_mt5_accounts_user_server', 'mt5_accounts', ['user_id', 'server_id'], unique=False)
    op.create_table('mt5_sync_log',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('sync_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('record_count', sa.Numeric(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('sync_duration_ms', sa.Numeric(), nullable=True),
    sa.Column('sync_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('sync_completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('mt5_server_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=True),
    sa.Column('type', sa.Enum('ACCOUNT_UPDATE', 'TRADE_ALERT', 'RISK_VIOLATION', 'SYSTEM_ALERT', 'ACCOUNT_PASSED', 'ACCOUNT_FAILED', 'PAYMENT_CONFIRMED', 'DAILY_SUMMARY', 'WEEKLY_REPORT', 'PLATFORM_ANNOUNCEMENT', name='notificationtypeenum'), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('data', sa.Text(), nullable=True),
    sa.Column('priority', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'URGENT', name='notificationpriorityenum'), nullable=False),
    sa.Column('channels', sa.Text(), nullable=False),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'DELIVERED', 'FAILED', 'READ', name='notificationstatusenum'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('delivery_attempts', sa.Numeric(), nullable=False),
    sa.Column('last_delivery_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('is_dismissed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_scheduled_for', 'notifications', ['scheduled_for'], unique=False)
    op.create_index('ix_notifications_type_priority', 'notifications', ['type', 'priority'], unique=False)
    op.create_index('ix_notifications_user_status', 'notifications', ['user_id', 'status'], unique=False)
    op.create_table('trades',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('order_type', sa.String(length=10), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('open_price', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('close_price', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('stop_loss', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('take_profit', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('commission', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('swap', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('open_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('close_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('magic_number', sa.Numeric(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_trades_account_ticket', 'trades', ['account_id', 'ticket_id'], unique=True)
    op.create_table('mt5_trades',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('platform_trade_id', sa.UUID(), nullable=True),
    sa.Column('mt5_ticket', sa.String(length=50), nullable=False),
    sa.Column('symbol', sa.String(length=20), nullable=False),
    sa.Column('direction', sa.Enum('BUY', 'SELL', name='mt5tradedirectionenum'), nullable=False),
    sa.Column('volume', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('price_open', sa.Numeric(precision=12, scale=5), nullable=False),
    sa.Column('price_close', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('time_open', sa.DateTime(timezone=True), nullable=False),
    sa.Column('time_close', sa.DateTime(timezone=True), nullable=True),
    sa.Column('time_update', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'CLOSED', 'CANCELED', name='mt5tradestatusenum'), nullable=False),
    sa.Column('reason', sa.String(length=50), nullable=True),
    sa.Column('profit', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('swap', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('commission', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('sl', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('tp', sa.Numeric(precision=12, scale=5), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('magic_number', sa.Numeric(), nullable=True),
    sa.Column('is_external', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['mt5_accounts.id'], ),
    sa.ForeignKeyConstraint(['platform_trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_index('ix_mt5_trades_account_ticket', 'mt5_trades', ['account_id', 'mt5_ticket'], unique=True)
    op.create_index('ix_mt5_trades_status_time', 'mt5_trades', ['status', 'time_open'], unique=False)
    op.create_table('violations',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('violation_type', sa.Enum('DAILY_LOSS_EXCEEDED', 'TOTAL_LOSS_EXCEEDED', 'MAX_POSITIONS_EXCEEDED', 'UNAUTHORIZED_INSTRUMENT', 'OUTSIDE_TRADING_HOURS', 'MAX_LOT_SIZE_EXCEEDED', 'MANUAL_FAIL', name='violationtypeenum'), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('current_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('threshold_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('symbol', sa.String(length=20), nullable=True),
    sa.Column('trade_id', sa.UUID(), nullable=True),
    sa.Column('is_resolved', sa.Boolean(), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.UUID(), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['trade_id'], ['trades.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('account_status_history',
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('from_status', sa.Enum('CREATED', 'PENDING', 'ACTIVE', 'PASSED', 'FAILED', 'LOCKED', 'ARCHIVED', name='accountstatusenum'), nullable=True),
    sa.Column('to_status', sa.Enum('CREATED', 'PENDING', 'ACTIVE', 'PASSED', 'FAILED', 'LOCKED', 'ARCHIVED', name='accountstatusenum'), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('change_reason', sa.Text(), nullable=False),
    sa.Column('change_notes', sa.Text(), nullable=True),
    sa.Column('violation_id', sa.UUID(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['violation_id'], ['violations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('account_status_history')
    op.drop_table('violations')
    op.drop_index('ix_mt5_trades_status_time', table_name='mt5_trades')
    op.drop_index('ix_mt5_trades_account_ticket', table_name='mt5_trades')
    op.drop_table('mt5_trades')
    op.drop_index('ix_trades_account_ticket', table_name='trades')
    op.drop_table('trades')
    op.drop_index('ix_notifications_user_status', table_name='notifications')
    op.drop_index('ix_notifications_type_priority', table_name='notifications')
    op.drop_index('ix_notifications_scheduled_for', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_table('mt5_sync_log')
    op.drop_index('ix_mt5_accounts_user_server', table_name='mt5_accounts')
    op.drop_index('ix_mt5_accounts_status', table_name='mt5_accounts')
    op.drop_table('mt5_accounts')
    op.drop_index('ix_equity_snapshots_account_timestamp', table_name='equity_snapshots')
    op.drop_table('equity_snapshots')
    op.drop_index('ix_daily_stats_account_date', table_name='daily_stats')
    op.drop_table('daily_stats')
    op.drop_table('account_rule_snapshots')
    op.drop_table('revenue_ledger')
    op.drop_table('accounts')
    op.drop_table('user_settings')
    op.drop_table('user_notification_settings')
    op.drop_table('trader_metrics')
    op.drop_table('payments')
    op.drop_table('login_audit_log')
    op.drop_index('ix_leaderboard_cache_period_user_rank', table_name='leaderboard_cache')
    op.drop_table('leaderboard_cache')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('ix_email_queue_template_id', table_name='email_queue')
    op.drop_index('ix_email_queue_status_priority', table_name='email_queue')
    op.drop_index('ix_email_queue_scheduled_for', table_name='email_queue')
    op.drop_table('email_queue')
    op.drop_table('challenge_rule_versions')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_table('platform_metrics')
    op.drop_table('notification_templates')
    op.drop_table('mt5_servers')
    op.drop_table('job_execution_log')
    op.drop_table('challenges')
    # ### end Alembic commands ###
