"""create_affiliate_system_tables

Revision ID: 7beb4c8ae7a8
Revises: f8107c801793
Create Date: 2026-03-01 18:57:29.578600

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7beb4c8ae7a8'
down_revision: Union[str, None] = 'f8107c801793'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
