"""add_monetization_tables

Revision ID: e5f719f45cc4
Revises: 7beb4c8ae7a8
Create Date: 2026-03-01 19:00:31.461176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5f719f45cc4'
down_revision: Union[str, None] = '7beb4c8ae7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('affiliates',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('referral_code', sa.String(length=50), nullable=False),
    sa.Column('tier', sa.Enum('TIER_1', 'TIER_2', 'TIER_3', 'ELITE', 'ENTERPRISE', name='affiliatetierenum'), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_type', sa.Enum('LIFETIME', 'ONE_TIME', name='commissiontypeenum'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('total_referred_users', sa.Integer(), nullable=False),
    sa.Column('total_revenue_generated', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('pending_commissions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('paid_commissions', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('average_revenue_per_user', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('payout_threshold', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('last_payout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id'),
    sa.UniqueConstraint('referral_code'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('referrals',
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('referred_user_id', sa.UUID(), nullable=True),
    sa.Column('referral_code_used', sa.String(length=50), nullable=False),
    sa.Column('commission_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('commission_type', sa.Enum('LIFETIME', 'ONE_TIME', name='commissiontypeenum'), nullable=False),
    sa.Column('commission_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_paid', sa.Boolean(), nullable=False),
    sa.Column('commission_paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referred_user_registered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referred_user_first_purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('referred_user_total_spent', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['referred_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    op.create_table('affiliate_commissions',
    sa.Column('affiliate_id', sa.UUID(), nullable=False),
    sa.Column('referral_id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('commission_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_by', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['processed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('affiliate_commissions')
    op.drop_table('referrals')
    op.drop_table('affiliates')
    # ### end Alembic commands ###
