"""add_last_evaluated_at_to_accounts

Revision ID: f8107c801793
Revises: 7ae8ba41fb86
Create Date: 2026-03-01 18:51:09.128811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8107c801793'
down_revision: Union[str, None] = '7ae8ba41fb86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account_rule_snapshots', ['id'])
    op.create_unique_constraint(None, 'account_status_history', ['id'])
    op.add_column('accounts', sa.Column('last_evaluated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_unique_constraint(None, 'accounts', ['id'])
    op.create_unique_constraint(None, 'challenge_rule_versions', ['id'])
    op.create_unique_constraint(None, 'challenges', ['id'])
    op.create_unique_constraint(None, 'daily_stats', ['id'])
    op.create_unique_constraint(None, 'email_queue', ['id'])
    op.create_unique_constraint(None, 'equity_snapshots', ['id'])
    op.create_unique_constraint(None, 'job_execution_log', ['id'])
    op.create_unique_constraint(None, 'leaderboard_cache', ['id'])
    op.create_unique_constraint(None, 'login_audit_log', ['id'])
    op.create_unique_constraint(None, 'mt5_accounts', ['id'])
    op.create_unique_constraint(None, 'mt5_servers', ['id'])
    op.create_unique_constraint(None, 'mt5_sync_log', ['id'])
    op.create_unique_constraint(None, 'mt5_trades', ['id'])
    op.create_unique_constraint(None, 'notification_templates', ['id'])
    op.create_unique_constraint(None, 'notifications', ['id'])
    op.create_unique_constraint(None, 'payments', ['id'])
    op.create_unique_constraint(None, 'platform_metrics', ['id'])
    op.create_unique_constraint(None, 'revenue_ledger', ['id'])
    op.create_unique_constraint(None, 'roles', ['id'])
    op.create_unique_constraint(None, 'trader_metrics', ['id'])
    op.create_unique_constraint(None, 'trades', ['id'])
    op.create_unique_constraint(None, 'user_notification_settings', ['id'])
    op.create_unique_constraint(None, 'user_settings', ['id'])
    op.create_unique_constraint(None, 'users', ['id'])
    op.create_unique_constraint(None, 'violations', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'violations', type_='unique')
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_constraint(None, 'user_settings', type_='unique')
    op.drop_constraint(None, 'user_notification_settings', type_='unique')
    op.drop_constraint(None, 'trades', type_='unique')
    op.drop_constraint(None, 'trader_metrics', type_='unique')
    op.drop_constraint(None, 'roles', type_='unique')
    op.drop_constraint(None, 'revenue_ledger', type_='unique')
    op.drop_constraint(None, 'platform_metrics', type_='unique')
    op.drop_constraint(None, 'payments', type_='unique')
    op.drop_constraint(None, 'notifications', type_='unique')
    op.drop_constraint(None, 'notification_templates', type_='unique')
    op.drop_constraint(None, 'mt5_trades', type_='unique')
    op.drop_constraint(None, 'mt5_sync_log', type_='unique')
    op.drop_constraint(None, 'mt5_servers', type_='unique')
    op.drop_constraint(None, 'mt5_accounts', type_='unique')
    op.drop_constraint(None, 'login_audit_log', type_='unique')
    op.drop_constraint(None, 'leaderboard_cache', type_='unique')
    op.drop_constraint(None, 'job_execution_log', type_='unique')
    op.drop_constraint(None, 'equity_snapshots', type_='unique')
    op.drop_constraint(None, 'email_queue', type_='unique')
    op.drop_constraint(None, 'daily_stats', type_='unique')
    op.drop_constraint(None, 'challenges', type_='unique')
    op.drop_constraint(None, 'challenge_rule_versions', type_='unique')
    op.drop_constraint(None, 'accounts', type_='unique')
    op.drop_column('accounts', 'last_evaluated_at')
    op.drop_constraint(None, 'account_status_history', type_='unique')
    op.drop_constraint(None, 'account_rule_snapshots', type_='unique')
    # ### end Alembic commands ###
